---
docker_old_packages:
  - docker
  - docker-engine
  - docker.io
  - containerd
  - runc
  
docker_required_packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  
docker_new_packages:
#  - docker.io
  - docker-ce
  - docker-ce-cli
  - containerd.io

