---
- name: check for docker_compose installation
  shell: "which docker-compose"
  register: result
  ignore_errors: true
  tags:
    - install
      
- name: install docker_compose
  become: yes
  apt:
    name: "{{ docker_compose_package }}"
    state: latest  
  when: ansible_facts.os_family == "Debian"
  when: result.rc == 1 
  tags:
    - install  

