#Check current docker version
- name: check for docker installation and current version
  command: docker --version
  register: docker_current_version
  changed_when: false
  failed_when: false
  check_mode: no
  tags:
    - always
    
- debug:
    msg: >
      Docker is install on your system
      "{{ docker_current_version.stdout }}"
  when: docker_current_version.rc == 0
       
#Exit process if docker install
- name: Exit if docker installed
  meta: end_play
  when: docker_current_version.rc == 0
  tags:
    - force update


#Going to redhat.yaml on redhat-based
- include_tasks: redhat.yaml
  name: For Redhat-based
  when: ansible_os_family == 'RedHat'

#Going to debian.yaml in debian-based
- include_tasks: debian.yaml
  name: For Debian-based
  when: ansible_os_family == 'Debian'



