---  
- name: check for docker installation
  shell: "which docker"
  register: result
  ignore_errors: true
  tags:
    - install
      
- name: install docker
  become: yes
  apt:
    name: "{{ docker_package }}"
    state: latest
  when: ansible_facts.os_family == "Debian"
  when: result.rc == 1  
  tags:
    - install  
    
- name: update docker
  become: yes
  apt:
    update_cache: yes
    upgrade: yes
  when: result.rc == 0  
  tags:
    - update  
    
    

    
