- name: update yum cache and update system
  shell: yum update -y
    tags:
      - update

- name: Add Docker GPG key.
  rpm_key:
    key: "{{ docker_yum_gpg_key }}"
    state: present

 
- name: install docker latest version
  yum:
    name: "{{ docker_new_packages }}"
    update_cache: yes
    state: present
  tags: 
    - install
